#!/usr/bin/env bash
# scripts/ard_workspace.sh
#
# Create (or refresh) the ARD "workspace" branch with all task reward functions
# purged. The ARD framework regenerates each task's reward from scratch, so we
# give it a clean slate: a dedicated `workspace` branch whose `_get_rewards`
# bodies are blanked (they just `return zeros`). No reference reward leaks into
# the LLM prompt. Success tracking and the `fitness_function` metric live
# OUTSIDE `_get_rewards`, so purging never touches the score ARD is judged on.
#
# Usage:
#   scripts/ard_workspace.sh [--base <ref>] [--force] [--dry-run] [--no-commit]
#
#   --base <ref>   Branch/commit to build `workspace` from. Default: current branch.
#   --force        If `workspace` already exists, delete and recreate it.
#   --dry-run      Print the git/purge commands without running them.
#   --no-commit    Purge but leave the changes uncommitted for review.
set -euo pipefail

BRANCH="workspace"
TASKS_DIR="source/ard_tasks/ard_tasks/tasks/direct"
PURGE="scripts/purge_rewards.py"
RETURN_STMT="return torch.zeros(self.num_envs, device=self.device)"

BASE=""
FORCE=0
DRY_RUN=0
COMMIT=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base)      BASE="${2:?--base needs a ref}"; shift 2 ;;
    --force)     FORCE=1; shift ;;
    --dry-run)   DRY_RUN=1; shift ;;
    --no-commit) COMMIT=0; shift ;;
    -h|--help)   sed -n '2,17p' "$0"; exit 0 ;;
    *) echo "error: unknown argument '$1'" >&2; exit 2 ;;
  esac
done

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

run() { echo "+ $*"; [[ $DRY_RUN -eq 1 ]] || "$@"; }

# 1. Refuse to run on a dirty tree so we never sweep unrelated edits into workspace.
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "error: working tree has uncommitted changes; commit or stash them first." >&2
  exit 1
fi

# 2. Resolve the base branch (default: current). It must not be `workspace` itself.
CURRENT="$(git rev-parse --abbrev-ref HEAD)"
[[ -z "$BASE" ]] && BASE="$CURRENT"
if [[ "$BASE" == "$BRANCH" ]]; then
  echo "error: base resolves to '$BRANCH'; pass --base <ref> (e.g. --base main)." >&2
  exit 1
fi
if ! git rev-parse --verify --quiet "$BASE^{commit}" >/dev/null; then
  echo "error: base ref '$BASE' does not exist." >&2
  exit 1
fi

# 3. Handle an existing workspace branch.
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  if [[ $FORCE -eq 1 ]]; then
    run git switch "$BASE"
    run git branch -D "$BRANCH"
  else
    echo "error: branch '$BRANCH' already exists. Re-run with --force to recreate it." >&2
    exit 1
  fi
fi

# 4. Create workspace from base, then blank every _get_rewards body.
run git switch -c "$BRANCH" "$BASE"
run python "$PURGE" --return-stmt "$RETURN_STMT" "$TASKS_DIR"

# 5. Commit the purge (unless --no-commit).
if [[ $COMMIT -eq 1 ]]; then
  run git add -A
  run git commit -m "chore(ard): purge reference rewards on workspace branch

Blank every _get_rewards body (return zeros) so the ARD reward generator
starts from a clean slate with no reference reward as prior knowledge.
Success tracking and the fitness_function metric live outside _get_rewards
and are unaffected. Generated by scripts/ard_workspace.sh."
else
  echo "purge complete; changes left uncommitted (--no-commit)."
fi

echo "done: on branch '$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "$BRANCH")' (base '$BASE')."
